markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: David.CM
url: http://www.david.cm
description: Projects and stuff.
twitter: tmdchi
github: davidcm
gravatar_url: http://gravatar.com/avatar/3c8f4803c4e4dae10f9e4d6743fe72c2
