pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-redirect-from

name: david.cm
url: http://david.cm
description: My independent professional self.
twitter: tmdchi
github: davidcm
gravatar_url: http://gravatar.com/avatar/3c8f4803c4e4dae10f9e4d6743fe72c2

me: <a href='http://www.david.cm'>Me</a>
rtypex: <a href='http://rtypex.com'>Ángel García</a>
ferminho: <a href='http://twitter.com/ferminho'>Fermín Vicente</a>
alvaro: <a href='http://www.twitter.com/alopfr'>Álvaro López</a>
atic2a: <a href='http://www.atic2a.com'>Atic2a</a>
bud: <a href='http://twitter.com/budsan_'>Jordi Santiago</a>
xavi: <a href='http://twitter.com/xavimator'>Xavi Segura</a>
lugallegos: <a href='http://twitter.com/Lu_Gallegos'>Lucía Gallegos</a>
diego: <a href='http://www.diegomunoz.es'>Diego Muñoz</a>
ismael: <a href='http://es.linkedin.com/pub/ismael-vega/9/212/905/es'>Ismael Vega</a>
3dkiwi: <a href='https://juan3d.artstation.com/'>Juan González</a>
pau: <a href='http://www.paudamiariera.com'>Pau Damià Riera</a>
raulj: Raúl Jordano

download: <i class="icon icon-download-alt"></i>